### ISSUE TITLE
Game of Light lootgame round timeout removes acknowledgements (1.7.10)

### ISSUE THREAD

**Issue by TopPercentageRattata** [TimeConqueror/LootGames#5]
If a light game times out then it bugs out and removes all structure acknologments, at least on 1.7.10, giving 0 chests and spawning lava.

Context:
I was on last round of light lootgames on GTNH(MC 1.7.10, 1.0.18 of your mod, 2.1.0.0 of modpack) and server I was on had a lag spike after 4th level started, so I waited a bit so that I wouldn't accidentally click something twice.
But server lag spike lasted too long and so round failed, so I just purposely failed the rest of the rounds wanting to get my 3 chests that I should have gotten, since getting to 4th level takes a long time of waiting.
But the game ended up being a "failure" with the floor being turned to lava and 0 chests appearing.

**Comment by TimeConqueror** [comment]
LootGames was rewritten for 1.7.10 , try new version marked as 2 :D
